version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.12"

sphinx:
  fail_on_warning: false
  configuration: docs/source/conf.py

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
    - requirements: requirements.txt
